### Kowope Mart is a Nigerian-based retail company with a vision to provide quality goods, education and automobile services to its customers at affordable price and reduce if not eradicate charges on card payments and increase customer satisfaction with credit rewards that can be used within the Mall. To achieve this, the company has partnered with DSBank on co-branded credit card with additional functionality such that customers can request for loan, pay for goods even with zero-balance and then pay back within an agreed period of time. 

### This innovative strategy has increased sales for the company. However, there has been recent cases of credit defaults and Kowope Mart will like to have a system that profiles customers who are worthy of the card with minimum if not zero risk of defaulting.You have been employed as a Data Scientist to leverage Machine learning to predict customers who are likely to default or not.This is Qualification Competition for the Data Science Nigeria AI Bootcamp.

## The data is a structure dataset pull from the Kowope Mart’s database with few important features that can be used to predict defaulters in retail network. The data sample has been split into train and test with a volume of 56,000 and 24,000.

## The files for download are:
### train.csv - you will use this to train your model.
### test.csv - you will use this to test your model.
### SampleSubmission.csv - is an example of what your submission file should look like. The order of the rows does not matter, but the names of the UIDs must be correct. You must predict growth_stage for the corresponding images.

## Variables

##### Application_ID: Unique Customer Application Identification number



### Risk Scoring features: There's a minimum payments you are expected to make on your lines of credit or credit cards at certain periods, when you miss those payments. Your credit score is affected and you are in delinquency period. Every credit cards and lines of credits impacts Risk scoring significantly. High credit card balance could lower your credit scores even with one time payments, if it raises your credit utilization ratio. Scoring models don't consider lines of credit when calculating revolving utilization ratio.

#### form_field1: Customer Creditworthiness score based on historical data. 
###### (Important feature affected by repayment history, type of credit, new credit, current debt, length of credit. (Determines ability to borrow money, ranks borrower's riskiness but not borrower's default probability, does not account for economic conditions). 800-850 excellent, Very good 740-799, Good 670-739, Fair 580-669, Poor 300-579. Payment history accounts for 35% of credit score, Total owed 30%, Length of credit history counts 15% longer credit histories 10% type of credits, new credits 10% credit inquiries

##### form_field2: A score that measures the number and riskiness of credit enquiries made by a borrower. (Related to no of enquiries for credit. usually there is a riskiness limit, the more the riskier. (studies show people with 6-8 inquiries are more likely to file for bankruptcy). Multiple enquiries lowers your credit score

### Severity features: Severity is a function of amount, time since default, and number of defaults

#### form_field3: Severity of default by the borrower on any loan(s).
#### form_field4: Severity of default by the borrower on auto loan(s). (Auto loans are usually backed by collateral)
#### form_field5: Severity of default by the borrower on education loan(s).


### Credit features
#### form_field6: Minimum of credit available on all credit cards that is automatically renewed as debts are paid off on the customer’s cards (in NGN) (The smaller credit limit of a particular card)
#### form_field7: Maximum of credit available on customer’s active credit lines (in NGN)
#### form_field8: Maximum of credit available on all active credit cards that is automatically renewed as debts are paid off on the customer’s cards (in NGN) (Max credit limit of a card)
#### form_field9: Sum of available credit on credit cards that the borrower has missed 1 payment (in NGN)  (Borrower already missed one payment, is currently in deliquency period before default. What is now the sum of available credit on those credit cards, is borrower still nearing default.
#### form_field10: Total amount of credit available on accepted credit lines (in NGN) (Credit status)
#### form_field11: The amount of dues collected post-default where the due amount was more than 500 (in NGN) (penalty dues post-default collected)
#### form_field12: Sum of the amount due on active credit cards (in NGN) (Statement balance)
#### form_field13: Annual amount paid towards all credit cards during the previous year (in NGN) 
#### form_field14: Annual income (in NGN)
#### form_field15: The estimated market value of a property owned/used by the borrower (in NGN)


### Credit card features:
#### form_field16: Number of active credit card that is automatically renewed as debts are paid off on which full credit limit is utilized by the borrower 
#### form_field17: Number of active credit cards on which full credit limit is utilized by the borrower
#### form_field18: Number of active credit lines on which full credit limit is utilized by the borrower
#### form_field19: Number of active credit cards on which at least 75% credit limit is utilized by the borrower
#### form_field20: Number of active credit lines on which at least 75% credit limit is utilized by the borrower
#### form_field21: Average utilization of active revolving credit card loans (%)
#### form_field22: Average utilization of line on all active credit lines activated in last 2 years (%)
#### form_field23: Average utilization of line on all active credit cards activated in last 1 year (%)
#### form_field24: Average utilization of line on credit cards on which the borrower has missed 1 payment during the last 6 months (%)

## Tenure is pre-agreed time period (in months or years) between the lender and borrower, for the borrower to repay the principal and interest in full to the lender
#### form_field25: Average tenure of active revolving credit cards (in days) (Average tenure of revolving credits on credit cards, balance not paid yet)
#### form_field26: Tenure of oldest credit card among all active credit cards (in days)
#### form_field27: Tenure of oldest revolving credit card among all active revolving credit cards (in days)


### Time-related features:
#### form_field28: Number of days since last missed payment on any credit line
#### form_field29: Tenure of the oldest credit line (in days)
#### form_field30: Maximum tenure on all auto loans (in days)
#### form_field31: Maximum tenure on all education loans (in days)
#### form_field32: Sum of tenures (in months) of active credit cards
#### form_field33: Sum of tenures (in months) of active credit cards
#### form_field34: Number of active credit lines over the last 6 months on which the borrower has missed 1 payment
#### form_field35: Number of revolving credit cards over the last 2 years on which the borrower has missed 1 payment
#### form_field36: Number of active credit lines
#### form_field37: Number of credit cards with an active tenure of at least 2 years
#### form_field38: Number of credit lines activated in the last 2 years
#### form_field39: Number of credit lines on which the borrower has current delinquency (Period between missing a loan payment and having the loan default, it's like a grace period after loan expiry date before penalizing the borrower after missing a payment).


### Percentage related features:
#### form_field40: Utilization of line on active education loans (%)
#### form_field41: Utilization of line on active auto loans (%)


### Other features:
#### form_field42: Financial stress index of the borrower. This index is a function of collection trades, bankruptcies files, tax liens invoked, etc.
#### form_field43: Number of credit lines on which the borrower has never missed a payment in the last 2 years, yet considered as high-risk loans based on the market prediction of the economic scenario
#### form_field44: Ratio of the maximum amount due on all active credit lines and the sum of amounts due on all active credit lines
#### form_field45: Number of mortgage loans on which the borrower has missed 2 payments
#### form_field46: Number of auto loans on which the borrower has missed 2 payments
#### form_field47: Type of product that the applicant applied for. (C = Charge; L = Lending)
#### form_field48: Undefined Variable
#### form_field49: Undefined Variable
#### form_field50: Ratio of the minimum amount due on all active credit lines and the sum of amounts due on all active credit lines


### Target features:
#### default_status: defaulted or not. (yes:1, no: 0)

#### This risk prediction can be approached as a binary classification utilizing the most predictive features. In this notebook we focus on analyzing and preparing the data to achieve the optimum AUC score on the credit default risk prediction.

In [1]:
#import necessary dependecies
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
import math
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import os
import warnings
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, log_loss
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from scipy.stats import mode
from sklearn.metrics import silhouette_score
from itertools import permutations
from tqdm import tqdm
#import swifter
from itertools import combinations
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit, cross_val_score, KFold, GridSearchCV, StratifiedKFold
from sklearn.metrics import balanced_accuracy_score, auc, mean_squared_error, roc_curve, confusion_matrix, precision_score, recall_score, f1_score,\
log_loss, roc_auc_score
from sklearn.impute import SimpleImputer
#from imblearn.over_sampling import SMOTE
#from imblearn.pipeline import Pipeline

%matplotlib inline
warnings.filterwarnings('ignore')
from typing import List

In [2]:
os.getcwd()

'/Users/mac/Documents/AIIP/Competitions/Credit-default'

In [3]:
#Load the datasets

train = pd.read_csv('train.csv')

test = pd.read_csv('test.csv')

submission = pd.read_csv('Submission.csv')

In [4]:
print(train.shape, test.shape, submission.shape)

(56000, 53) (24000, 52) (24000, 3)

In [5]:
train.head()

,Unnamed: 0,Applicant_ID,Creditworthiness_score,CreditEnquiredRisk,LoanDefaultSeverityAll,LoanDefaultSeverityAuto,LoanDefaultSeverityEdu,MinCreditAvailAfterPayments,MaxCreditAvailActiveAll,MaxCreditAvailAfterPayments,...,FinanceStressIndex,NumberCLinesPaidHighRisk,DebtRatio1Max,NumOfHomeLoansMissed2x,NumOfAutoLoansMissed2x,form_field48,form_field49,DebtRatio1Min,ProductApplicatn,default_status
0,0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,...,0.392854,2.02,0.711632,0.0,0.0,NaN,1.129518,0.044335,1,1
1,1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,...,0.314281,8.08,0.183584,NaN,0.0,349.805730,1.620483,0.322436,1,1
2,2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,...,0.162965,18.18,0.791136,0.0,0.0,NaN,1.513370,0.011640,1,0
3,3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,...,0.488884,2.02,0.685168,NaN,0.0,89.940100,0.664452,0.082729,1,1
4,4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,...,0.275000,12.12,0.438168,0.0,0.0,97.887502,1.427891,0.045630,1,1

In [6]:
test.head()

,Unnamed: 0,Applicant_ID,Creditworthiness_score,CreditEnquiredRisk,LoanDefaultSeverityAll,LoanDefaultSeverityAuto,LoanDefaultSeverityEdu,MinCreditAvailAfterPayments,MaxCreditAvailActiveAll,MaxCreditAvailAfterPayments,...,%UseCLinesonAutoLoan,FinanceStressIndex,NumberCLinesPaidHighRisk,DebtRatio1Max,NumOfHomeLoansMissed2x,NumOfAutoLoansMissed2x,form_field48,form_field49,DebtRatio1Min,ProductApplicatn
0,0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,...,NaN,0.825000,1.01,0.800000,NaN,0.0,NaN,0.000000,0.011221,1
1,1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,...,18.8415,0.507694,4.04,0.623248,1.0,0.0,NaN,0.504974,0.043525,0
2,2,Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,0.000000,NaN,1
3,3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,...,NaN,0.916663,2.02,0.464224,NaN,NaN,90.163742,0.788809,0.104029,1
4,4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,...,NaN,0.234047,23.23,0.726688,0.0,0.0,1303.587148,1.637733,0.163124,0

In [7]:
submission.head()

   Unnamed: 0   Applicant_ID  default_status
0           0  Apcnt_1000032               1
1           1  Apcnt_1000048               1
2           2  Apcnt_1000052               1
3           3  Apcnt_1000076               1
4           4  Apcnt_1000080               1

In [8]:
#Renaming the columns to make more interpretable

rename_col = {"form_field1":'Creditworth_score',
           "form_field2":'CreditEnquiredRisk',
           "form_field3":'LoanDefaultSeverityAll',
           "form_field4":'LoanDefaultSeverityAuto',
           "form_field5":'LoanDefaultSeverityEdu',
           "form_field6":'MinCreditAvailAfterPaymentsCards',
           "form_field7":'MaxCreditAvailActivelines',
           "form_field8":'MaxCreditAvailAfterPaymentsCards',
           "form_field9":'SumOfAvailCreditOnCardsMissed1Pay',
                                            
           "form_field10":'TotalCreditAvailActivelines',
           "form_field11":'PostDefaultDuesCollectedA500',
                                            
           "form_field12":'TotalDueActiveCards',
           "form_field13":'AnnualPaidPreviousYearAllCards',
                                            
           "form_field14":'AnnualIncome',
           "form_field15":'PropertyMarketValue',
                                            
           "form_field16":'NumActiveCCardsRenewedFullCreditUsed',
           "form_field17":'NumActiveCCardsFullCreditUsed',
                                            
           "form_field18":'NumActiveCLinesFullCreditUsed',
           "form_field19":'NumActiveCCards75pCreditUsed',
                                            
           "form_field20":'NumActiveCLines75pCreditUsed',
           "form_field21":'%AverageUtilCCard',
                                            
           "form_field22":'%AvgUtilOfCLines2Yrs',
           "form_field23":'%AvgUtilOfCCards1Yr',
                                            
           "form_field24":'%AvgUtilOfCLines6MoMiss1',
           "form_field25":'AvgTenureofActiveRevolveCardsinDays',
                                            
           "form_field26":'TenureofOldestCCardsinDays',
           "form_field27":'TenureofOldestRevolveCCardsinDays',
                                            
           "form_field28":'NumDaysonlastmissedCLine',
           "form_field29":'TenureofOldestCLineinDays',
                                            
           "form_field30":'MaxTenureonAutoLoansinDays',
           "form_field31":'MaxTenureonEduLoansinDays',
                                            
           "form_field32":'SumTenureonActiveCCardsinMonth',
           "form_field33":'SumTenureonActiveCLinesinMonth',
                                            
           "form_field34":'NumOfCLineslast6MoMiss1', 
           "form_field35":'NumOfRevolveCCardslast2YrMiss1',
                                            
           "form_field36":'NumActiveCLines',
           "form_field37":'NumCCardsActiveTenure2Yrs',
                                            
           "form_field38":'NumActivatedCLinesinlast2Yrs',
           "form_field39":'NumActiveCLinesDeliquent',
                                            
           "form_field40":'%UtilCLinesonEduLoan',
           "form_field41":'%UtilCLinesonAutoLoan',
                                            
           
           
           "form_field42":'FinanceStressIndex',
           "form_field43":'NumberCLinesPaidHighRisk',
                                            
           "form_field44":'RatioDueCCLinesMaxSumCCLines',
           "form_field45":'NumOfMortgageLoansMissed2x',
                                            
           "form_field46":'NumOfAutoLoansMissed2x',
           "form_field50": 'RatioDueCCLinesMinSumCCLines',
                                            
           'form_field47': 'ProductType', 
              
           'default_status_no': 'default_status'}

In [9]:
train = train.rename(columns = rename_col)

test = test.rename(columns = rename_col)

In [10]:
train.head()

,Unnamed: 0,Applicant_ID,Creditworthiness_score,CreditEnquiredRisk,LoanDefaultSeverityAll,LoanDefaultSeverityAuto,LoanDefaultSeverityEdu,MinCreditAvailAfterPayments,MaxCreditAvailActiveAll,MaxCreditAvailAfterPayments,...,FinanceStressIndex,NumberCLinesPaidHighRisk,DebtRatio1Max,NumOfHomeLoansMissed2x,NumOfAutoLoansMissed2x,form_field48,form_field49,DebtRatio1Min,ProductApplicatn,default_status
0,0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,...,0.392854,2.02,0.711632,0.0,0.0,NaN,1.129518,0.044335,1,1
1,1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,...,0.314281,8.08,0.183584,NaN,0.0,349.805730,1.620483,0.322436,1,1
2,2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,...,0.162965,18.18,0.791136,0.0,0.0,NaN,1.513370,0.011640,1,0
3,3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,...,0.488884,2.02,0.685168,NaN,0.0,89.940100,0.664452,0.082729,1,1
4,4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,...,0.275000,12.12,0.438168,0.0,0.0,97.887502,1.427891,0.045630,1,1

In [11]:
test.head()

,Unnamed: 0,Applicant_ID,Creditworthiness_score,CreditEnquiredRisk,LoanDefaultSeverityAll,LoanDefaultSeverityAuto,LoanDefaultSeverityEdu,MinCreditAvailAfterPayments,MaxCreditAvailActiveAll,MaxCreditAvailAfterPayments,...,%UseCLinesonAutoLoan,FinanceStressIndex,NumberCLinesPaidHighRisk,DebtRatio1Max,NumOfHomeLoansMissed2x,NumOfAutoLoansMissed2x,form_field48,form_field49,DebtRatio1Min,ProductApplicatn
0,0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,...,NaN,0.825000,1.01,0.800000,NaN,0.0,NaN,0.000000,0.011221,1
1,1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,...,18.8415,0.507694,4.04,0.623248,1.0,0.0,NaN,0.504974,0.043525,0
2,2,Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,0.000000,NaN,1
3,3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,...,NaN,0.916663,2.02,0.464224,NaN,NaN,90.163742,0.788809,0.104029,1
4,4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,...,NaN,0.234047,23.23,0.726688,0.0,0.0,1303.587148,1.637733,0.163124,0

In [12]:
train.dtypes

Unnamed: 0                                   int64
Applicant_ID                                object
Creditworthiness_score                     float64
CreditEnquiredRisk                         float64
LoanDefaultSeverityAll                     float64
LoanDefaultSeverityAuto                    float64
LoanDefaultSeverityEdu                     float64
MinCreditAvailAfterPayments                float64
MaxCreditAvailActiveAll                    float64
MaxCreditAvailAfterPayments                float64
SumOfAvailCreditMissed1Pay                 float64
TotalCreditAvailActiveAll                  float64
PostDefaultDuesCollectedA500               float64
TotalDueActive                             float64
AllAnnualPaidPreviousYear                  float64
AnnualIncome                                 int64
PropertyMarketValue                        float64
NumActiveCCardsPaidOffFullCreditUsed       float64
NumActiveCCardsFullCreditUsed              float64
NumActiveFullCLinesFullCreditUsed          float64
NumActiveCCards75pCreditUsed               float64
NumActiveCLines75pCreditUsed               float64
%AverageUseOfCCardLoans                    float64
%AverageUseOfCLines2Yrs                    float64
%AverageUseOfCCards1Yr                     float64
%AverageUseOfCLines6MoMiss1                float64
AverageTenureofActiveRevolveCardsinDays    float64
TenureofOldestCCardsinDays                 float64
TenureofOldestRevolvingCCardsinDays        float64
NumOfDaysonlastmissedCLine                 float64
TenureofOldestCLineinDays                  float64
MaxTenureonAutoLoansinDays                 float64
MaxTenureonEduLoansinDays                  float64
SumTenureonActiveCCardsinMonth             float64
SumTenureonActiveCLinesinMonth             float64
NumOfCLineslast6MoMiss1                    float64
NumOfRevolveCCardslast2YrMiss1             float64
NumActiveCLines                            float64
NumCCardsActiveTenure2Yrs                  float64
ActivatedCLinesinlast2Yrs                  float64
NumActiveCLinesDeliquent                   float64
%UseCLinesonEduLoan                        float64
%UseCLinesonAutoLoan                       float64
FinanceStressIndex                         float64
NumberCLinesPaidHighRisk                   float64
DebtRatio1Max                              float64
NumOfHomeLoansMissed2x                     float64
NumOfAutoLoansMissed2x                     float64
form_field48                               float64
form_field49                               float64
DebtRatio1Min                              float64
ProductApplicatn                             int64
default_status                               int64
dtype: object

Mostly numerical variables with ProductType categorical

## EDA:

### Data Overview:

In [13]:
#Merging train and test for joint analysis

train['combiner'] = 'x'
test['combiner'] = 'y'

In [14]:
data = pd.concat([train, test])

In [15]:
data.reset_index(drop = True, inplace = True)

In [16]:
data.head()

,%AverageUseOfCCardLoans,%AverageUseOfCCards1Yr,%AverageUseOfCLines2Yrs,%AverageUseOfCLines6MoMiss1,%UseCLinesonAutoLoan,%UseCLinesonEduLoan,ActivatedCLinesinlast2Yrs,AllAnnualPaidPreviousYear,AnnualIncome,Applicant_ID,...,TenureofOldestCCardsinDays,TenureofOldestCLineinDays,TenureofOldestRevolvingCCardsinDays,TotalCreditAvailActiveAll,TotalDueActive,Unnamed: 0,combiner,default_status,form_field48,form_field49
0,134.655,NaN,NaN,134.655,NaN,NaN,4.0,7875694.0,96375139,Apcnt_1000000,...,17064.0,17064.0,11376.0,11333126.0,2301324.0,0,x,1.0,NaN,1.129518
1,109.230,14584.29,11385.24,86.685,NaN,NaN,8.0,2141445.0,28141427,Apcnt_1000004,...,13413.0,13413.0,8942.0,2533168.0,3982971.0,1,x,1.0,349.805730,1.620483
2,NaN,NaN,NaN,NaN,NaN,149.6805,6.0,0.0,16576457,Apcnt_1000008,...,4746.0,15696.0,3164.0,1079864.0,NaN,2,x,0.0,NaN,1.513370
3,120.120,0.00,8580.00,85.800,NaN,NaN,4.0,1186839.0,48187375,Apcnt_1000012,...,4014.0,11679.0,2676.0,3621979.0,771776.0,3,x,1.0,89.940100,0.664452
4,104.535,10326.45,8360.19,115.335,NaN,150.0135,24.0,511535.0,28141427,Apcnt_1000016,...,3285.0,19437.0,2190.0,361770.0,818456.0,4,x,1.0,97.887502,1.427891

In [17]:
data.tail()

,%AverageUseOfCCardLoans,%AverageUseOfCCards1Yr,%AverageUseOfCLines2Yrs,%AverageUseOfCLines6MoMiss1,%UseCLinesonAutoLoan,%UseCLinesonEduLoan,ActivatedCLinesinlast2Yrs,AllAnnualPaidPreviousYear,AnnualIncome,Applicant_ID,...,TenureofOldestCCardsinDays,TenureofOldestCLineinDays,TenureofOldestRevolvingCCardsinDays,TotalCreditAvailActiveAll,TotalDueActive,Unnamed: 0,combiner,default_status,form_field48,form_field49
79995,NaN,NaN,NaN,NaN,92.6910,NaN,6.0,0.0,21973443,Apcnt_999940,...,NaN,3741.0,NaN,2280318.0,NaN,23995,y,NaN,NaN,0.000000
79996,123.195,NaN,11663.055,123.195,125.0220,NaN,8.0,97696961.0,96375139,Apcnt_999956,...,6387.0,14691.0,4258.0,12999991.0,48989882.0,23996,y,NaN,4200.072959,3.000000
79997,NaN,NaN,13080.000,NaN,NaN,NaN,2.0,0.0,21973443,Apcnt_999976,...,NaN,10038.0,NaN,49403.0,NaN,23997,y,NaN,NaN,4.855060
79998,129.435,13024.995,13024.995,138.450,31.1955,NaN,4.0,673748.0,16576457,Apcnt_999984,...,2463.0,6297.0,1642.0,2551062.0,355935.0,23998,y,NaN,27.325129,0.818733
79999,NaN,NaN,NaN,124.980,112.3035,NaN,0.0,3031477.0,48187375,Apcnt_999992,...,30204.0,30204.0,20136.0,5361587.0,0.0,23999,y,NaN,NaN,0.000000

In [18]:
data.describe()

,%AverageUseOfCCardLoans,%AverageUseOfCCards1Yr,%AverageUseOfCLines2Yrs,%AverageUseOfCLines6MoMiss1,%UseCLinesonAutoLoan,%UseCLinesonEduLoan,ActivatedCLinesinlast2Yrs,AllAnnualPaidPreviousYear,AnnualIncome,AverageTenureofActiveRevolveCardsinDays,...,SumTenureonActiveCLinesinMonth,TenureofOldestCCardsinDays,TenureofOldestCLineinDays,TenureofOldestRevolvingCCardsinDays,TotalCreditAvailActiveAll,TotalDueActive,Unnamed: 0,default_status,form_field48,form_field49
count,57439.000000,39752.000000,50876.000000,61098.000000,25422.000000,17443.000000,79498.000000,7.164800e+04,8.000000e+04,72294.000000,...,78249.000000,69390.000000,79498.000000,66791.000000,7.949800e+04,6.592200e+04,80000.000000,56000.000000,5.018900e+04,79499.000000
mean,86.685145,6458.894743,6635.784763,104.972751,108.145137,147.746178,8.572845,6.002145e+06,7.627971e+07,2625.097954,...,13.993114,10107.365543,16515.352235,6193.160306,1.186153e+07,2.771394e+06,23199.500000,0.755089,3.041331e+05,1.053579
std,53.365748,5797.309660,5673.072482,450.120664,36.663235,44.643599,7.928927,2.226305e+07,3.068579e+09,1959.001865,...,15.300278,8793.726717,9667.958861,5390.116309,2.613218e+07,4.621145e+06,15846.023853,0.430038,1.717065e+06,1.809372
min,0.255000,0.000000,0.000000,0.000000,0.000000,0.021000,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.166600,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
25%,40.395000,811.736250,1090.072500,14.838750,87.229500,136.033500,4.000000,1.941110e+05,1.657646e+07,1231.500000,...,2.333400,3375.000000,9765.000000,2068.000000,4.411260e+05,2.746340e+05,9999.750000,1.000000,7.706548e+01,0.000000
50%,89.535000,5550.000000,5961.637500,60.660000,118.325250,150.000000,6.000000,1.591010e+06,2.814143e+07,2208.000000,...,7.833400,8214.000000,15057.000000,5110.000000,3.692582e+06,1.158248e+06,19999.500000,1.000000,3.167076e+02,0.000000
75%,129.930000,11281.425000,11368.946250,114.810000,137.459625,167.547000,12.000000,5.590027e+06,4.818738e+07,3529.125000,...,21.333400,14145.000000,21810.000000,8638.000000,1.323592e+07,3.368740e+06,35999.250000,1.000000,1.167000e+03,1.200961
max,1957.875000,186799.995000,97200.000000,41801.100000,255.000000,645.450000,190.000000,2.457824e+09,3.854990e+11,25093.500000,...,152.000000,73275.000000,73914.000000,44104.000000,2.191361e+09,1.609235e+08,55999.000000,1.000000,1.213991e+08,28.000000

In [19]:
data.isnull().sum()

%AverageUseOfCCardLoans                    22561
%AverageUseOfCCards1Yr                     40248
%AverageUseOfCLines2Yrs                    29124
%AverageUseOfCLines6MoMiss1                18902
%UseCLinesonAutoLoan                       54578
%UseCLinesonEduLoan                        62557
ActivatedCLinesinlast2Yrs                    502
AllAnnualPaidPreviousYear                   8352
AnnualIncome                                   0
Applicant_ID                                   0
AverageTenureofActiveRevolveCardsinDays     7706
CreditEnquiredRisk                          5553
Creditworthiness_score                      3639
DebtRatio1Max                               7745
DebtRatio1Min                              15853
FinanceStressIndex                          1901
LoanDefaultSeverityAll                       501
LoanDefaultSeverityAuto                      501
LoanDefaultSeverityEdu                       501
MaxCreditAvailActiveAll                     7394
MaxCreditAvailAfterPayments                18964
MaxTenureonAutoLoansinDays                 36417
MaxTenureonEduLoansinDays                  56218
MinCreditAvailAfterPayments                18964
NumActiveCCards75pCreditUsed                   4
NumActiveCCardsFullCreditUsed              15846
NumActiveCCardsPaidOffFullCreditUsed       18510
NumActiveCLines                             2898
NumActiveCLines75pCreditUsed                 502
NumActiveCLinesDeliquent                    6040
NumActiveFullCLinesFullCreditUsed          14771
NumCCardsActiveTenure2Yrs                   7706
NumOfAutoLoansMissed2x                     22789
NumOfCLineslast6MoMiss1                      502
NumOfDaysonlastmissedCLine                   502
NumOfHomeLoansMissed2x                     44855
NumOfRevolveCCardslast2YrMiss1             33014
NumberCLinesPaidHighRisk                     818
PostDefaultDuesCollectedA500               44819
ProductApplicatn                               0
PropertyMarketValue                        32067
SumOfAvailCreditMissed1Pay                 11408
SumTenureonActiveCCardsinMonth              7706
SumTenureonActiveCLinesinMonth              1751
TenureofOldestCCardsinDays                 10610
TenureofOldestCLineinDays                    502
TenureofOldestRevolvingCCardsinDays        13209
TotalCreditAvailActiveAll                    502
TotalDueActive                             14078
Unnamed: 0                                     0
combiner                                       0
default_status                             24000
form_field48                               29811
form_field49                                 501
dtype: int64

There are significant null values, not all credit variables is available.

In [20]:
#Percentage of null values per feature

data.isnull().sum()/len(data)

%AverageUseOfCCardLoans                    0.282012
%AverageUseOfCCards1Yr                     0.503100
%AverageUseOfCLines2Yrs                    0.364050
%AverageUseOfCLines6MoMiss1                0.236275
%UseCLinesonAutoLoan                       0.682225
%UseCLinesonEduLoan                        0.781963
ActivatedCLinesinlast2Yrs                  0.006275
AllAnnualPaidPreviousYear                  0.104400
AnnualIncome                               0.000000
Applicant_ID                               0.000000
AverageTenureofActiveRevolveCardsinDays    0.096325
CreditEnquiredRisk                         0.069413
Creditworthiness_score                     0.045488
DebtRatio1Max                              0.096812
DebtRatio1Min                              0.198162
FinanceStressIndex                         0.023762
LoanDefaultSeverityAll                     0.006262
LoanDefaultSeverityAuto                    0.006262
LoanDefaultSeverityEdu                     0.006262
MaxCreditAvailActiveAll                    0.092425
MaxCreditAvailAfterPayments                0.237050
MaxTenureonAutoLoansinDays                 0.455213
MaxTenureonEduLoansinDays                  0.702725
MinCreditAvailAfterPayments                0.237050
NumActiveCCards75pCreditUsed               0.000050
NumActiveCCardsFullCreditUsed              0.198075
NumActiveCCardsPaidOffFullCreditUsed       0.231375
NumActiveCLines                            0.036225
NumActiveCLines75pCreditUsed               0.006275
NumActiveCLinesDeliquent                   0.075500
NumActiveFullCLinesFullCreditUsed          0.184638
NumCCardsActiveTenure2Yrs                  0.096325
NumOfAutoLoansMissed2x                     0.284863
NumOfCLineslast6MoMiss1                    0.006275
NumOfDaysonlastmissedCLine                 0.006275
NumOfHomeLoansMissed2x                     0.560688
NumOfRevolveCCardslast2YrMiss1             0.412675
NumberCLinesPaidHighRisk                   0.010225
PostDefaultDuesCollectedA500               0.560238
ProductApplicatn                           0.000000
PropertyMarketValue                        0.400838
SumOfAvailCreditMissed1Pay                 0.142600
SumTenureonActiveCCardsinMonth             0.096325
SumTenureonActiveCLinesinMonth             0.021888
TenureofOldestCCardsinDays                 0.132625
TenureofOldestCLineinDays                  0.006275
TenureofOldestRevolvingCCardsinDays        0.165112
TotalCreditAvailActiveAll                  0.006275
TotalDueActive                             0.175975
Unnamed: 0                                 0.000000
combiner                                   0.000000
default_status                             0.300000
form_field48                               0.372638
form_field49                               0.006262
dtype: float64

Initially we will leave all null values and build a baseline model with null values, also as we continue with analysis, we will decide how to handle nulls per features.

In [21]:
#Categorical variables

data.describe(include = 'object')

         Applicant_ID combiner
count           80000    80000
unique          80000        2
top     Apcnt_1150732        x
freq                1    56000

In [22]:
data['Applicant_ID'].nunique()

80000

In [23]:
#Checking duplicated columns

len(data[data.duplicated()])

0

#### Build Quick Baseline Model

In [24]:
#Label Encode Product Type

labenc = LabelEncoder()

data['ProductType'] = labenc.fit_transform (data['ProductType'])

KeyError: 'ProductType'

In [25]:
# imp_cols = list(set(data.columns) - set(data[['Applicant_ID', 'combiner','default_status']]))

In [26]:
# data_imp = data.copy()

In [27]:
# imp_mean =SimpleImputer(missing_values = np.nan, strategy = 'mean')

# data_imp[imp_cols] = imp_mean.fit_transform(data_imp[imp_cols])

In [28]:
train = data[data['combiner'] == 'x']

In [29]:
labstat = LabelEncoder()

train['default_status'] = labstat.fit_transform(train['default_status'])

In [30]:
target = train[['default_status']]

#### LightGbm Baseline

In [31]:
target['default_status']

0        1
1        1
2        0
3        1
4        1
        ..
55995    1
55996    0
55997    1
55998    1
55999    1
Name: default_status, Length: 56000, dtype: int64

In [ ]:
#Cross-Validation routine

from lightgbm import LGBMClassifier

from xgboost import XGBClassifier

rand = 40

fold = StratifiedKFold(n_splits= 5, shuffle= True, random_state= rand)

i = 1

err = []

#Standardize
#scaler = StandardScaler()

for train_index, test_index in fold.split(train, target):

    print('fold n°: ', i)

    x_data, x_val = train.iloc[train_index], train.iloc[test_index]

    y_data, y_val = target.iloc[train_index], target.iloc[test_index]
    
    

    x_data = x_data.drop(['default_status','combiner', 'Applicant_ID'], axis = 1)
    
    x_val = x_val.drop(['default_status','combiner', 'Applicant_ID'], axis = 1)
    
    
#     x_data['ProductType'].fillna(0.5, inplace = True)
    
#     x_val['ProductType'].fillna(0.5, inplace = True)
    
  
    lgb_model = LGBMClassifier(n_estimators = 1100, learning_rate = 0.01,  reg_lambda = 10, random_state = rand)
    
#     'subsample': 0.4, 'reg_alpha': 5, 'n_estimators': 1200, 'min_child_weight': 1, \
#                     'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0, 'colsample_bytree': 0.8}

     
        
    lgb_model.fit(x_data, y_data['default_status'].ravel(), eval_set= [(x_val, y_val['default_status'].ravel())], \
              early_stopping_rounds= 500,\
              verbose= 100, eval_metric = ['auc'])
        
    y_train_pred = lgb_model.predict_proba(x_data)[:,1]

    y_test_pred = lgb_model.predict_proba(x_val)[:,1]
    
    
    
        
    print('auc train', roc_auc_score(y_data, y_train_pred))
    print('auc test',  roc_auc_score(y_val, y_test_pred))
    
    
    
    err.append(roc_auc_score(y_val, y_test_pred))


    i = i + 1
        
print('Mean auc test: ', np.mean(err))

fold n°:  1
Training until validation scores don't improve for 500 rounds
[100]	valid_0's auc: 0.826648	valid_0's binary_logloss: 0.450922
[200]	valid_0's auc: 0.832201	valid_0's binary_logloss: 0.423709
[300]	valid_0's auc: 0.834526	valid_0's binary_logloss: 0.414636
[400]	valid_0's auc: 0.836473	valid_0's binary_logloss: 0.410622
[500]	valid_0's auc: 0.837476	valid_0's binary_logloss: 0.408986
[600]	valid_0's auc: 0.837969	valid_0's binary_logloss: 0.408234
[700]	valid_0's auc: 0.838164	valid_0's binary_logloss: 0.407876

In [ ]:
test = data[data['combiner'] == 'y']

In [ ]:
train.head()

In [ ]:
import lightgbm as lgb

#fitting the model

lgb_model.fit(train.drop(['default_status','combiner', 'Applicant_ID'], axis = 1), target['default_status'].ravel())


#Test set predictions

test['default_status']  = lgb_model.predict_proba(test.drop(['default_status', 'combiner', 'Applicant_ID'],\
                                                            axis = 1))[:,1]

In [ ]:
test['default_status'].head()

#### Exploring feature importance

In [ ]:
lgb.plot_importance(lgb_model, importance_type = "gain")

In [ ]:
zip_imp = zip(lgb_model.feature_importances_, train.drop(['default_status','combiner', 'Applicant_ID'], axis = 1).columns)

In [ ]:
feat_imp = list(zip_imp)

In [ ]:
feat_imp.sort(reverse = True)

In [ ]:
feat_imp

#### LightGBM Baseline score 0.842
#### EDA Continued:

In [ ]:
data['ProductType'] = labstat.inverse_transform(data['ProductType'])

In [ ]:
data.isnull().sum() / len(data)

#### Feature Relationships with Default Status

In [ ]:
data.columns

#### Create Baseline Submission

In [ ]:
submission.head()

In [ ]:
sub_test = test[['Applicant_ID', 'default_status']]

In [ ]:
sub_test.reset_index(drop = True, inplace = True)

In [ ]:
sub_test.to_csv("submission5.csv", index = False)

In [ ]:
sub_test